# Generated by Django 6.0 on 2026-01-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_genre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="piece_identite_document_url",
        ),
        migrations.AddField(
            model_name="user",
            name="document_piece_identite",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="pieces_identite/",
                verbose_name="Pièce d'identité",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="id_verification_status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("approved", "Approuvé"),
                    ("rejected", "Rejeté"),
                    ("manual", "Vérification manuelle"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="id_verified",
            field=models.BooleanField(default=False, verbose_name="Identité vérifiée"),
        ),
    ]
