# Generated by Django 6.0 on 2026-01-20 22:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_piece_identite_document_url_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={"verbose_name": "Rôle", "verbose_name_plural": "Rôles"},
        ),
        migrations.AlterField(
            model_name="user",
            name="document_piece_identite",
            field=models.ImageField(
                blank=True, null=True, upload_to="pieces_identite/"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="users.role",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="telephone",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Numéro sénégalais invalide",
                        regex="^\\+221(77|78|76|75|70)\\d{7}$",
                    )
                ],
            ),
        ),
    ]
