# Generated by Django 6.0 on 2026-01-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_role_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photo_profil",
            field=models.ImageField(
                default="profils/default.png", upload_to="profils/"
            ),
        ),
    ]
