# Generated by Django 6.0 on 2026-02-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_photo_profil"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="piece_identite_numero",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
