# Generated by Django 6.0 on 2026-01-06 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("centres", "0001_initial"),
        ("medecins", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="centresante",
            name="gerant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="centres_geres",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="medecincentre",
            name="centre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="centres.centresante"
            ),
        ),
        migrations.AddField(
            model_name="medecincentre",
            name="medecin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="medecins.medecin"
            ),
        ),
        migrations.AddField(
            model_name="medecincentre",
            name="specialite",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="centres.specialite",
            ),
        ),
        migrations.AddField(
            model_name="centresante",
            name="type_centre",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="centres.typecentre",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="medecincentre",
            unique_together={("medecin", "centre", "specialite")},
        ),
    ]
