# Generated by Django 6.0 on 2026-01-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("centres", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialite",
            name="description_specialite",
            field=models.TextField(blank=True, null=True),
        ),
    ]
