# Generated by Django 6.0 on 2026-01-06 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profil_patient",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notepatient",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="maladie",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maladies",
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="rappelpatient",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rappels",
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="resultatanalyse",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analyses",
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="maladie",
            name="resultat_analyse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="patients.resultatanalyse",
            ),
        ),
        migrations.AddField(
            model_name="resultatanalyse",
            name="type_analyse",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="patients.typeanalyse",
            ),
        ),
    ]
